# Generated by Django 6.0.5 on 2026-05-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('core', '0003_attendance_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalmail',
            name='related_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptance_mails', to='core.employeeprofile'),
        ),
        migrations.AddField(
            model_name='internalmail',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='internalmail',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='internalmail',
            name='mail_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('PROMOTION', 'Promotion Letter'), ('OFFER_ACCEPTANCE', 'Offer Acceptance')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='internalmail',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to=settings.AUTH_USER_MODEL),
        ),
    ]
