# Generated by Django 6.0.5 on 2026-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_internalmail_related_profile_offerletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmail',
            name='mail_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('PROMOTION', 'Promotion Letter'), ('OFFER_ACCEPTANCE', 'Offer Acceptance'), ('WISH', 'Wish'), ('LATE_WARNING', 'Late Warning')], default='GENERAL', max_length=20),
        ),
    ]
