# Generated by Django 6.0.5 on 2026-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeeprofile_onboarding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location_name',
            field=models.CharField(blank=True, help_text='Location name at time of check-in (department / office)', max_length=200),
        ),
    ]
