# Generated by Django 5.1.5 on 2026-05-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='Manager responsible for leave approvals and performance reviews', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='core.employeeprofile'),
        ),
    ]
