# Generated by Django 6.0.5 on 2026-05-13 15:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employeeprofile_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status_text', models.TextField(help_text='Detailed status of daily tasks and accomplishments.')),
                ('hours_logged', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_daily_work_log',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'profile'], name='core_daily__date_89b303_idx')],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
