# Generated by Django 6.0.5 on 2026-05-14 00:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeeprofile_blood_group_employeeprofile_hobbies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Expense title / description', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='reimbursements/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Verification'), ('HR_VERIFIED', 'HR Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('hr_verified_at', models.DateTimeField(blank=True, null=True)),
                ('md_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('md_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_requests', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_reimbursement_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_reimbu_status_dabafc_idx'), models.Index(fields=['profile', 'status'], name='core_reimbu_profile_093e5b_idx')],
            },
        ),
    ]
