# Generated by Django 5.2.14 on 2026-05-08 10:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone Handset"),
                            ("SIM", "SIM Card"),
                            ("LAPTOP", "Laptop / Workstation"),
                            ("ID_CARD", "ID Card"),
                            ("EQUIPMENT", "Other Equipment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Model / serial / phone number", max_length=160
                    ),
                ),
                ("serial_no", models.CharField(blank=True, max_length=120)),
                ("issued_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("RETURNED", "Returned"),
                            ("LOST", "Lost / Damaged"),
                        ],
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "assets_company_asset",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="NOC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(default="General", max_length=200)),
                (
                    "template_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="nocs/templates/%Y/"
                    ),
                ),
                (
                    "signed_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="nocs/signed/%Y/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("SIGNED", "Signed Returned"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nocs",
                        to="core.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "assets_noc",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisciplineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_on", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("LATE", "Late attendance escalation"),
                            ("ATTN", "Other attendance violation"),
                            ("OTHER", "Other"),
                        ],
                        default="LATE",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("WARN", "Warning (email)"),
                            ("HALF", "0.5 day cut"),
                            ("FULL", "1.0 day cut"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "deduction_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Days to deduct in payroll for this record",
                        max_digits=4,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="HR can revoke"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discipline_records",
                        to="core.attendance",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discipline_records",
                        to="core.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "assets_discipline",
                "ordering": ["-occurred_on"],
                "indexes": [
                    models.Index(
                        fields=["profile", "occurred_on"],
                        name="assets_disc_profile_514c48_idx",
                    )
                ],
            },
        ),
    ]
