# Generated by Django 5.1.5 on 2026-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='duties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='job_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='probation_status',
            field=models.CharField(choices=[('PROBATION', 'Probation'), ('PERMANENT', 'Permanent')], default='PROBATION', max_length=20),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
