# Generated by Django 6.0.5 on 2026-05-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeeprofile_blood_group_employeeprofile_hobbies_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('BIRTHDAY_WISH', 'Birthday Wish'), ('ANNIVERSARY_WISH', 'Anniversary Wish'), ('ONBOARDING_WISH', 'Onboarding Wish'), ('PROMOTION_WISH', 'Promotion Wish'), ('LATE_WARNING', 'Late Warning')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notifications', to='core.employeeprofile'),
        ),
    ]
